// NextAuth (Auth.js v5) — Google sign-in, gated by ALLOWED_EMAILS.
//
// Anyone whose email isn't on the allowlist is rejected during the
// sign-in callback. The session stores the user's email so server-side
// code can scope listeners to its owner.
//
// Env vars (all required for sign-in to work):
//   AUTH_SECRET         — random 32+ byte string. Generated by
//                         `openssl rand -base64 32`.
//   AUTH_GOOGLE_ID      — Google OAuth client ID.
//   AUTH_GOOGLE_SECRET  — Google OAuth client secret.
//   ALLOWED_EMAILS      — comma-separated list of allowed emails.
//                         Lowercase comparison. Whitespace trimmed.

import NextAuth from "next-auth";
import Google from "next-auth/providers/google";

function parseAllowlist(raw: string | undefined): Set<string> {
  if (!raw) return new Set();
  return new Set(
    raw
      .split(",")
      .map((s) => s.trim().toLowerCase())
      .filter(Boolean),
  );
}

/** Is this email allowed to sign in? Empty allowlist = nobody. */
export function isAllowed(email: string | null | undefined): boolean {
  if (!email) return false;
  const allow = parseAllowlist(process.env.ALLOWED_EMAILS);
  return allow.has(email.toLowerCase());
}

export const { auth, handlers, signIn, signOut } = NextAuth({
  providers: [
    Google({
      clientId: process.env.AUTH_GOOGLE_ID,
      clientSecret: process.env.AUTH_GOOGLE_SECRET,
    }),
  ],
  // Vercel sits behind an edge proxy. Without this, Auth.js v5 refuses
  // forwarded host headers and shows an "UntrustedHost" / "proxy
  // detected" style error. Safe to enable for any deployment behind
  // a trusted reverse proxy.
  trustHost: true,
  pages: {
    signIn: "/login",
  },
  session: { strategy: "jwt" },
  callbacks: {
    /** Reject sign-ins from emails not on the allowlist. */
    async signIn({ user }) {
      return isAllowed(user.email);
    },
    /** Persist email + name into the JWT so middleware/API can use it. */
    async jwt({ token, user }) {
      if (user) {
        token.email = user.email ?? token.email;
        token.name = user.name ?? token.name;
        token.picture = user.image ?? token.picture;
      }
      return token;
    },
    /** Surface email + name + image to the client session. */
    async session({ session, token }) {
      if (session.user) {
        session.user.email = (token.email as string) ?? session.user.email;
        session.user.name = (token.name as string) ?? session.user.name;
        session.user.image =
          (token.picture as string) ?? session.user.image ?? null;
      }
      return session;
    },
  },
});
